console.log('level 0')
console.group()
    console.log('level 1')
    console.log('ok')
    console.group()
        console.log('level 2')
        console.log('no')
    console.groupEnd()
    console.log('level 1')
    console.log('end')
console.groupEnd()
console.log('End')
